name: Control de Compilación - Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Descargar código del repositorio
      uses: actions/checkout@v4


    - name: Configurar JDK de Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven' 

    - name: Asegurar permisos de ejecución para Maven
      run: chmod +x mvnw

    - name: Compilar proyecto con Maven (Sin Tests)
      run: ./mvnw clean package -DskipTests